/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.entidadesDTO.Reservacion;
import modelo.operacionesDAO.aulaDAO;
import modelo.operacionesDAO.reservacionDAO;

/**
 *
 * @author Anthony Tejada
 */
public class JFrameListarReservaciones extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListarReservaciones
     */
                ArrayList<Reservacion> lista = null;

    public JFrameListarReservaciones() {
        initComponents();
        cargarTablaReservaciones("", jComboBoxBuscar.getSelectedItem().toString());
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldbuscar = new javax.swing.JTextField();
        jComboBoxBuscar = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReservacion = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbuscarActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldbuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 120, -1));

        jComboBoxBuscar.setBackground(null);
        jComboBoxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "CODIGO", "ENCARGADO" }));
        getContentPane().add(jComboBoxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 66, -1));

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableReservacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableReservacion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 692, 280));

        jButton2.setBackground(null);
        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, -1, -1));

        jButton1.setBackground(null);
        jButton1.setText("Crear Reservacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondos/fondo_listar_reservacion_proyectoPOOParcial2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbuscarActionPerformed
        cargarTablaReservaciones(jTextFieldbuscar.getText(),jComboBoxBuscar.getSelectedItem().toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbuscarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         int fila = jTableReservacion.getSelectedRow();
        if(fila <0){
            JOptionPane.showMessageDialog(null,"Selecione una reservacion en la lista para eliminar");
        }else{
             int i = JOptionPane.showConfirmDialog((Component)evt.getSource(),
                "Esta Seguro de Eliminar una Reservacion?", "Mensaje",
                JOptionPane.YES_NO_OPTION);
        
        if(i==JOptionPane.YES_NO_OPTION){   
               
            EliminarReservacion();
        }
        }
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrameNuevaReservacion obj = new JFrameNuevaReservacion();
        obj.setVisible(true);
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
     private void EliminarReservacion(){
    reservacionDAO OBJ  = new reservacionDAO();
    int fila = jTableReservacion.getSelectedRow();
   if( OBJ.eliminarPorId(Integer.parseInt( jTableReservacion.getValueAt(fila, 0).toString()))==1){
       JOptionPane.showMessageDialog(null, "Eliminacion correcta de RESERVACION ");
       cargarTablaReservaciones("", jComboBoxBuscar.getSelectedItem().toString());
   }else{
              JOptionPane.showMessageDialog(null, "ERROR, No se puede eliminar una Reservacion");

   }
}
    private void cargarTablaReservaciones(String buscar, String tipo){
        reservacionDAO reservdao = new reservacionDAO();
        aulaDAO obj = new aulaDAO ();
        lista = reservdao.consultaReservacionPorTipo(buscar,tipo);
        
        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnas = {"ID","ID_AULA","Codigo","Encargado","Hora_Inicio","Hora_Fin","Dia","Fecha"};
        modelo.setColumnIdentifiers(columnas);
        Object [] producto = new Object[8];
        for(int i = 0; i <lista.size(); i++){
            producto[0] = lista.get(i).getId_reservacion();
            producto[1] = lista.get(i).getId_aula();
            producto[2] = lista.get(i).getCodigo();
            producto[3] = lista.get(i).getEncargado();
            producto[4] = lista.get(i).getHora_inicio();
            producto[5] = lista.get(i).getHora_fin();
            producto[6] = lista.get(i).getDia_letra();
            producto[7] = lista.get(i).getDia()+"-"+lista.get(i).getMes()+"-"+lista.get(i).getAño();


            modelo.addRow(producto);

        }
        //establecer el modelo de al JTABLE
        jTableReservacion.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListarReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListarReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListarReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListarReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListarReservaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReservacion;
    private javax.swing.JTextField jTextFieldbuscar;
    // End of variables declaration//GEN-END:variables
}
