/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.entidadesDTO.Reservacion;
import modelo.operacionesDAO.aulaDAO;
import modelo.operacionesDAO.reservacionDAO;

/**
 *
 * @author Anthony Tejada
 */
public class JFrameListarReservaciones extends javax.swing.JFrame {

    /**
     * Creates new form JFrameListarReservaciones
     */
                ArrayList<Reservacion> lista = null;

    public JFrameListarReservaciones() {
        initComponents();
        cargarTablaReservaciones("", jComboBoxBuscar.getSelectedItem().toString());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldbuscar = new javax.swing.JTextField();
        jComboBoxBuscar = new javax.swing.JComboBox<>();
        jLabelBuscar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableReservacion = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextFieldbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbuscarActionPerformed(evt);
            }
        });

        jComboBoxBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "CODIGO", "ENCARGADO" }));

        jLabelBuscar.setText("Buscar:");

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableReservacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableReservacion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabelBuscar)
                .addGap(34, 34, 34)
                .addComponent(jTextFieldbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBuscar)
                    .addComponent(jTextFieldbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbuscarActionPerformed
        cargarTablaReservaciones(jTextFieldbuscar.getText(),jComboBoxBuscar.getSelectedItem().toString());
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbuscarActionPerformed
    private void cargarTablaReservaciones(String buscar, String tipo){
        reservacionDAO reservdao = new reservacionDAO();
        aulaDAO obj = new aulaDAO ();
        lista = reservdao.consultaReservacionPorTipo(buscar,tipo);
        
        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnas = {"ID","ID_AULA","Codigo","Encargado","Hora_Inicio","Hora_Fin","Dia","Fecha"};
        modelo.setColumnIdentifiers(columnas);
        Object [] producto = new Object[8];
        for(int i = 0; i <lista.size(); i++){
            producto[0] = lista.get(i).getId_reservacion();
            producto[1] = lista.get(i).getId_aula();
            producto[2] = lista.get(i).getCodigo();
            producto[3] = lista.get(i).getEncargado();
            producto[4] = lista.get(i).getHora_inicio();
            producto[5] = lista.get(i).getHora_fin();
            producto[6] = lista.get(i).getDia_letra();
            producto[7] = lista.get(i).getDia()+"-"+lista.get(i).getMes()+"-"+lista.get(i).getAño();


            modelo.addRow(producto);

        }
        //establecer el modelo de al JTABLE
        jTableReservacion.setModel(modelo);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameListarReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameListarReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameListarReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameListarReservaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameListarReservaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxBuscar;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableReservacion;
    private javax.swing.JTextField jTextFieldbuscar;
    // End of variables declaration//GEN-END:variables
}
