/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.entidadesDTO.Aula;
import modelo.operacionesDAO.aulaDAO;

/**
 *
 * @author Dexx
 */
public class JPanelListadoAulas extends javax.swing.JPanel {
    ArrayList<Aula> lista;
    aulaDAO objAulaDao = null;

    /**
     * Creates new form JPanelListadoAulas
     */
    public JPanelListadoAulas() {
        initComponents();
        cargarTabla("");
    }
   
public void cargarTabla(String criterio){
        aulaDAO auladao = new aulaDAO();
        lista = auladao.consultaAulas(criterio);
 

        //mostrar lista de productos en la tabla 
        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnas = {"ID","Codigo","idPaqueteDias","idReservacion","tipoAula"};
        modelo.setColumnIdentifiers(columnas);
        Object [] producto = new Object[5];
        for(int i = 0; i <lista.size(); i++){
            producto[0] = lista.get(i).getId();
            producto[1] = lista.get(i).getCodigo();
            producto[2] = lista.get(i).getIdDias();
            producto[3] = lista.get(i).getIdReservacion();
            producto[4] = lista.get(i).toString();
            System.out.println("tamaño de lista"+lista.size()+" tostring "+lista.get(i).toString());
            modelo.addRow(producto);

        }
        //establecer el modelo de al JTABLE
        jTableAula.setModel(modelo);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelBuscar = new javax.swing.JLabel();
        jTextFieldbuscar = new javax.swing.JTextField();
        jButtonBuscarAula = new javax.swing.JButton();
        jButtonNuevo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableAula = new javax.swing.JTable();

        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jLabelBuscar.setText("Buscar:");
        jPanel1.add(jLabelBuscar);
        jPanel1.add(jTextFieldbuscar);

        jButtonBuscarAula.setText("Buscar");
        jButtonBuscarAula.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonBuscarAulaMouseClicked(evt);
            }
        });
        jPanel1.add(jButtonBuscarAula);

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonNuevo);

        jButtonEditar.setText("Editar");
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar);

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar);

        add(jPanel1);

        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jTableAula.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableAula);

        add(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarAulaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonBuscarAulaMouseClicked
        cargarTabla(jTextFieldbuscar.getText());
    }//GEN-LAST:event_jButtonBuscarAulaMouseClicked

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
int i = JOptionPane.showConfirmDialog((Component)evt.getSource(),
                "Esta Seguro de Eliminar el Producto?", "Mensaje",
                JOptionPane.YES_NO_OPTION);
        
        if(i==JOptionPane.YES_NO_OPTION){
EliminarProducto();
        }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed

        JFrameNuevaAula obj = new JFrameNuevaAula();
        obj.setVisible(true);
        obj.setJFrameListar(this);

    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
               int fila = jTableAula.getSelectedRow();
                 String codigo  = jTableAula.getValueAt(fila,1).toString();

        
        JFrameEditarAula obj = new JFrameEditarAula(codigo);
        obj.setJFrameListar(this);
        obj.setVisible(true);
                

    }//GEN-LAST:event_jButtonEditarActionPerformed
private void EliminarProducto(){
    objAulaDao = new aulaDAO();
    int fila = jTableAula.getSelectedRow();
   if( objAulaDao.eliminarPorId(Integer.parseInt( jTableAula.getValueAt(fila, 0).toString()))==1){
       JOptionPane.showMessageDialog(null, "Eliminacion correcta de Aula");
       cargarTabla("");
   }else{
              JOptionPane.showMessageDialog(null, "ERROR Eliminacion correcta de Aula");

   }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarAula;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableAula;
    private javax.swing.JTextField jTextFieldbuscar;
    // End of variables declaration//GEN-END:variables
}
